[settings]
experimental = true

[settings.python]
compile = false

# Disable to avoid calling Github API
[settings.aqua]
cosign = false

[tools]
# https://github.com/gitleaks/gitleaks/releases
gitleaks = "8.30.1"

## Pre-commit and linting

# https://github.com/pre-commit/pre-commit/releases
pre-commit = "latest"
shellcheck = "latest"
actionlint = "latest"
