---
name: Build CV

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  static-analysis:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          echo "$HOME/.local/share/mise/shims" >> "$GITHUB_PATH"
      - name: Install mise tools
        run: |
          mise install
      - name: Install pre-commit hooks
        run: pre-commit install --install-hooks
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color=always

  build-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Build CV"
        run: ./build_in_docker.sh
      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release gnome ${{ github.ref }}
          draft: true
          files: |
            ./results/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # You don't need to add this in secrets it's by default.
